/** @type {import('tailwindcss').Config} */
// Токены повторяют дизайн-систему Stitch (yaride/DESIGN.md): Material-палитра,
// типографика Inter и скругления берём 1:1, чтобы экраны совпадали с макетами.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#fdfcff",
        "surface-container-high": "#e9e7ed",
        "tertiary-container": "#af6100",
        "inverse-surface": "#2f3034",
        "on-secondary-container": "#007521",
        "on-secondary-fixed-variant": "#005315",
        "primary-fixed": "#cce5ff",
        "surface-container-highest": "#e3e2e7",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#92ccff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001d31",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        outline: "#6f7881",
        "on-primary": "#ffffff",
        "primary-container": "#007bb9",
        surface: "#faf9fe",
        tertiary: "#8b4c00",
        "surface-container-low": "#f4f3f8",
        "tertiary-fixed-dim": "#ffb77a",
        "on-secondary-fixed": "#002204",
        "on-secondary": "#ffffff",
        "outline-variant": "#bfc7d2",
        "on-background": "#1a1b1f",
        "surface-variant": "#e3e2e7",
        primary: "#006193",
        "on-surface": "#1a1b1f",
        "on-error": "#ffffff",
        "surface-dim": "#dad9df",
        "secondary-fixed": "#7dfd82",
        secondary: "#006e1f",
        "tertiary-fixed": "#ffdcc2",
        "surface-bright": "#faf9fe",
        "inverse-on-surface": "#f1f0f5",
        "on-primary-fixed-variant": "#004b73",
        "primary-fixed-dim": "#92ccff",
        "secondary-container": "#7dfd82",
        "on-tertiary-container": "#fffbff",
        "on-surface-variant": "#3f4850",
        "secondary-fixed-dim": "#60e069",
        error: "#ba1a1a",
        "surface-container": "#eeedf3",
        "on-tertiary-fixed": "#2e1500",
        "surface-tint": "#006497",
        background: "#faf9fe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-page": "16px",
        "padding-card": "16px",
        "gutter-stack": "12px",
        "gap-chip": "8px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["17px", { lineHeight: "22px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "-0.1px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.1px", fontWeight: "600" }],
        "headline-md-mobile": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
