/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CreateRouteImport } from './routes/create'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripIdRouteImport } from './routes/trip.$id'
import { Route as RouteMapRouteImport } from './routes/route.map'
import { Route as RateIdRouteImport } from './routes/rate.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdRoute = TripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteMapRoute = RouteMapRouteImport.update({
  id: '/route/map',
  path: '/route/map',
  getParentRoute: () => rootRouteImport,
} as any)
const RateIdRoute = RateIdRouteImport.update({
  id: '/rate/$id',
  path: '/rate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/create': typeof CreateRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/history/$id': typeof HistoryIdRoute
  '/home': typeof HomeRoute
  '/license': typeof LicenseRoute
  '/manage': typeof ManageRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/rate/$id': typeof RateIdRoute
  '/route/map': typeof RouteMapRoute
  '/trip/$id': typeof TripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/create': typeof CreateRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/history/$id': typeof HistoryIdRoute
  '/home': typeof HomeRoute
  '/license': typeof LicenseRoute
  '/manage': typeof ManageRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/rate/$id': typeof RateIdRoute
  '/route/map': typeof RouteMapRoute
  '/trip/$id': typeof TripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/create': typeof CreateRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/history/$id': typeof HistoryIdRoute
  '/home': typeof HomeRoute
  '/license': typeof LicenseRoute
  '/manage': typeof ManageRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/rate/$id': typeof RateIdRoute
  '/route/map': typeof RouteMapRoute
  '/trip/$id': typeof TripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bookings'
    | '/create'
    | '/favorites'
    | '/history'
    | '/history/$id'
    | '/home'
    | '/license'
    | '/manage'
    | '/notifications'
    | '/onboarding'
    | '/search'
    | '/rate/$id'
    | '/route/map'
    | '/trip/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bookings'
    | '/create'
    | '/favorites'
    | '/history'
    | '/history/$id'
    | '/home'
    | '/license'
    | '/manage'
    | '/notifications'
    | '/onboarding'
    | '/search'
    | '/rate/$id'
    | '/route/map'
    | '/trip/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bookings'
    | '/create'
    | '/favorites'
    | '/history'
    | '/history/$id'
    | '/home'
    | '/license'
    | '/manage'
    | '/notifications'
    | '/onboarding'
    | '/search'
    | '/rate/$id'
    | '/route/map'
    | '/trip/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BookingsRoute: typeof BookingsRoute
  CreateRoute: typeof CreateRoute
  FavoritesRoute: typeof FavoritesRoute
  HistoryRoute: typeof HistoryRoute
  HistoryIdRoute: typeof HistoryIdRoute
  HomeRoute: typeof HomeRoute
  LicenseRoute: typeof LicenseRoute
  ManageRoute: typeof ManageRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  SearchRoute: typeof SearchRoute
  RateIdRoute: typeof RateIdRoute
  RouteMapRoute: typeof RouteMapRoute
  TripIdRoute: typeof TripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id': {
      id: '/trip/$id'
      path: '/trip/$id'
      fullPath: '/trip/$id'
      preLoaderRoute: typeof TripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/map': {
      id: '/route/map'
      path: '/route/map'
      fullPath: '/route/map'
      preLoaderRoute: typeof RouteMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate/$id': {
      id: '/rate/$id'
      path: '/rate/$id'
      fullPath: '/rate/$id'
      preLoaderRoute: typeof RateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BookingsRoute: BookingsRoute,
  CreateRoute: CreateRoute,
  FavoritesRoute: FavoritesRoute,
  HistoryRoute: HistoryRoute,
  HistoryIdRoute: HistoryIdRoute,
  HomeRoute: HomeRoute,
  LicenseRoute: LicenseRoute,
  ManageRoute: ManageRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  SearchRoute: SearchRoute,
  RateIdRoute: RateIdRoute,
  RouteMapRoute: RouteMapRoute,
  TripIdRoute: TripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
